name: CI - Upload Binaries

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_mojave:
    name: Zip and Upload Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          zip -r --symlinks 10.14-Mojave.zip 10.14-Mojave
          zip -r --symlinks 10.15-Catalina.zip 10.15-Catalina
          zip -r --symlinks 11-Big-Sur.zip 11-Big-Sur
          zip -r --symlinks 12-Monterey.zip 12-Monterey
      - name: Generate Checksums
        run: sha256sum *.zip > sha256sum.txt
      - run: |
          mkdir deploy
          mv *.zip sha256sum.txt deploy/
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          file_glob: true
